/** Shared, dependency-free capsule state. The DOM is never the source of truth. */
export const SCHEMA='language-canvas/intention@1';
export const MAX_BYTES=10000000;
export const PART_KINDS=['intent','outcome','audience','deliverables','requirements','constraints','structure','execution','verification','delivery','interaction','data','recovery','security','method','evidence','alternatives','voice','continuity','direction','assets','operations','economics','materials','safety','reference'];
export class IntentionError extends Error { constructor(code,message,status=400){super(message);this.code=code;this.status=status;} }
export const fail=(code,message,status=400)=>{throw new IntentionError(code,message,status);};
const copy=value=>structuredClone(value);
export const uid=()=>globalThis.crypto.randomUUID();
const now=()=>new Date().toISOString();
const isObject=v=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
function object(v,keys){if(!isObject(v)||Object.keys(v).some(k=>!keys.includes(k))||keys.some(k=>!(k in v)))fail('SCHEMA','The file or request contains unsupported or missing fields.');}
function text(v,max=30000,empty=true){if(typeof v!=='string'||v.length>max||(!empty&&!v.trim())||v.includes('\u0000'))fail('SCHEMA','A text value is missing or exceeds its allowed size.');return v;}
function id(v){if(typeof v!=='string'||!/^[a-zA-Z0-9_-]{1,80}$/.test(v))fail('SCHEMA','Invalid record identifier.');return v;}
function list(v,max){if(!Array.isArray(v)||v.length>max)fail('SCHEMA','A list is missing or exceeds its allowed size.');return v;}
function unique(values){if(new Set(values).size!==values.length)fail('SCHEMA','Duplicate identifiers are not allowed.');}
function timestamp(value){if(typeof value!=='string'||!/^\d{4}-\d\d-\d\dT/.test(value)||!Number.isFinite(Date.parse(value)))fail('SCHEMA','Invalid timestamp.');}
export function validateScope(scope,project){object(scope,['type','partId']);if(!['whole','part'].includes(scope.type)||scope.type==='whole'&&scope.partId!==null||scope.type==='part'&&!project.parts.some(p=>p.id===scope.partId))fail('SCOPE','Choose the whole intention or an existing part.');return scope;}
const SOURCE_KEYS=['title','intention','constraints','acceptance','parts','decisions'];
export function sourceOf(project){return Object.fromEntries(SOURCE_KEYS.map(key=>[key,copy(project[key])]));}
function validateSource(p){
 text(p.title,120,false);text(p.intention,10000);for(const key of ['constraints','acceptance'])list(p[key],64).forEach(v=>text(v,2000,false));
 list(p.parts,128).forEach(part=>{object(part,['id','parentId','title','kind','content','dependsOn','locked']);id(part.id);if(!PART_KINDS.includes(part.kind))fail('SCHEMA','Invalid document part kind.');if(part.parentId!==null)id(part.parentId);text(part.title,120,false);text(part.content);if(typeof part.locked!=='boolean')fail('SCHEMA','Invalid part lock.');list(part.dependsOn,128).forEach(id);unique(part.dependsOn);});
 unique(p.parts.map(v=>v.id));const ids=new Set(p.parts.map(v=>v.id));
 for(const part of p.parts){if(part.parentId!==null&&!ids.has(part.parentId)||part.dependsOn.some(v=>!ids.has(v)||v===part.id))fail('GRAPH','A part refers to an unknown or self-dependent part.');let at=part,seen=new Set();while(at){if(seen.has(at.id))fail('GRAPH','Parts cannot contain a cycle.');seen.add(at.id);at=p.parts.find(x=>x.id===at.parentId);}}
 const visiting=new Set(),done=new Set();function visit(part){if(visiting.has(part.id))fail('GRAPH','Dependencies cannot contain a cycle.');if(done.has(part.id))return;visiting.add(part.id);part.dependsOn.forEach(v=>visit(p.parts.find(x=>x.id===v)));visiting.delete(part.id);done.add(part.id);}p.parts.forEach(visit);
 list(p.decisions,256).forEach(d=>{object(d,['id','question','why','partIds','status','answer']);id(d.id);text(d.question,2000,false);text(d.why,3000,false);list(d.partIds,128).forEach(v=>{if(!ids.has(v))fail('GRAPH','Decision refers to an unknown part.');});if(!['pending','answered','dismissed'].includes(d.status))fail('SCHEMA','Unknown decision status.');text(d.answer,6000);if(d.status==='answered'&&!d.answer.trim())fail('SCHEMA','Answered decisions need an answer.');});unique(p.decisions.map(v=>v.id));
}
function validateChange(change,project){object(change,['partId','title','kind','content','parentId','dependsOn','before']);id(change.partId);if(!PART_KINDS.includes(change.kind))fail('SCHEMA','Invalid proposed document role.');text(change.title,120,false);text(change.content);if(change.parentId!==null)id(change.parentId);list(change.dependsOn,128).forEach(id);if(change.before!==null){object(change.before,['id','parentId','title','kind','content','dependsOn','locked']);const existing=project.parts.find(p=>p.id===change.partId);if(!existing||JSON.stringify(change.before)!==JSON.stringify(existing))fail('STALE_PROPOSAL','The proposed change no longer matches the current source.',409);}else if(project.parts.some(p=>p.id===change.partId))fail('STALE_PROPOSAL','A proposed new part already exists.',409);}
export function validateProposal(proposal,project){object(proposal,['id','baseRevision','scope','instruction','summary','primary','related','decisions','contextCheck','model','createdAt','primaryAccepted']);id(proposal.id);if(!Number.isSafeInteger(proposal.baseRevision)||proposal.baseRevision!==project.revision)fail('STALE_PROPOSAL','This proposal belongs to an older revision.',409);validateScope(proposal.scope,project);text(proposal.instruction,6000);text(proposal.summary,6000,false);text(proposal.model,200,false);timestamp(proposal.createdAt);if(typeof proposal.primaryAccepted!=='boolean')fail('SCHEMA','Invalid proposal state.');object(proposal.contextCheck,['mode','summary','partIds']);if(!['model','structural-only'].includes(proposal.contextCheck.mode))fail('SCHEMA','Invalid context check.');text(proposal.contextCheck.summary,6000,false);list(proposal.contextCheck.partIds,128).forEach(v=>{if(!project.parts.some(p=>p.id===v))fail('SCOPE','Context check names an unknown part.');});
 list(proposal.primary,128).forEach(c=>validateChange(c,project));list(proposal.related,128).forEach(c=>validateChange(c,project));unique([...proposal.primary,...proposal.related].map(c=>c.partId));
 if(proposal.scope.type==='part'){if(proposal.primary.some(c=>c.partId!==proposal.scope.partId)||proposal.related.some(c=>c.partId===proposal.scope.partId))fail('SCOPE','A part instruction cannot rewrite another part without separate approval.');}
 if(proposal.primaryAccepted&&proposal.primary.length)fail('SCHEMA','Accepted primary changes must no longer be pending.');
 for(const c of [...proposal.primary,...proposal.related])if(project.parts.find(p=>p.id===c.partId)?.locked)fail('LOCKED','A proposed change targets a locked part.',423);
 // Validate each acceptance phase independently; related work cannot be a hidden prerequisite.
 const phase=copy(project);applyChanges(phase,proposal.primary);validateSource(phase);applyChanges(phase,proposal.related);validateSource(phase);
 list(proposal.decisions,64).forEach(d=>{object(d,['question','why','partIds']);text(d.question,2000,false);text(d.why,3000,false);list(d.partIds,128).forEach(v=>{if(!project.parts.some(p=>p.id===v)&&!proposal.primary.some(c=>c.partId===v))fail('SCOPE','A decision must refer to existing or primary parts, not unapproved related work.');});});return proposal;
}
export function validateProject(project){
 object(project,['schema','id','revision','createdAt','updatedAt',...SOURCE_KEYS,'messages','history','pending']);if(project.schema!==SCHEMA)fail('VERSION','Unsupported capsule version. Keep the original file and use a compatible application.');id(project.id);if(!Number.isSafeInteger(project.revision)||project.revision<0)fail('SCHEMA','Invalid revision.');timestamp(project.createdAt);timestamp(project.updatedAt);validateSource(project);
 list(project.messages,1000).forEach(m=>{object(m,['id','scope','role','text','at']);id(m.id);object(m.scope,['type','partId']);if(!['whole','part'].includes(m.scope.type)||m.scope.type==='whole'&&m.scope.partId!==null||m.scope.type==='part'&&typeof m.scope.partId!=='string')fail('SCOPE','Invalid conversation scope.');if(!['user','assistant','local'].includes(m.role))fail('SCHEMA','Invalid conversation role.');text(m.text,12000,false);timestamp(m.at);});unique(project.messages.map(m=>m.id));
 list(project.history,2000).forEach(h=>{object(h,['revision','at','type','summary','before']);if(!Number.isSafeInteger(h.revision)||h.revision<1||h.revision>project.revision)fail('SCHEMA','Invalid history revision.');timestamp(h.at);text(h.type,100,false);text(h.summary,1000,false);if(h.before!==null){object(h.before,SOURCE_KEYS);validateSource(h.before);}});if(project.history.some((h,i)=>i&&h.revision<=project.history[i-1].revision))fail('SCHEMA','History must be ordered.');
 if(project.pending!==null)validateProposal(project.pending,project);if(new TextEncoder().encode(JSON.stringify(project)).length>MAX_BYTES)fail('SIZE','This capsule exceeds the 10 MB safety limit. Nothing was replaced.');return project;
}
export function createProject(intention='',title='Untitled intention'){const at=now();return validateProject({schema:SCHEMA,id:uid(),revision:0,createdAt:at,updatedAt:at,title,intention,constraints:[],acceptance:[],parts:[],decisions:[],messages:[],history:[],pending:null});}
export function importProject(value){if(typeof value==='string'){if(value.length>MAX_BYTES)fail('SIZE','This capsule exceeds the 10 MB safety limit.');try{value=JSON.parse(value);}catch{fail('JSON','This is not a valid capsule JSON file.');}}return copy(validateProject(value));}
function applyChanges(project,changes){for(const change of changes){const value={id:change.partId,parentId:change.parentId,title:change.title,kind:change.kind,content:change.content,dependsOn:change.dependsOn,locked:false};const index=project.parts.findIndex(p=>p.id===change.partId);if(index<0)project.parts.push(value);else project.parts[index]={...project.parts[index],...value};}}
export function proposalFromResult(project,scope,instruction,result,model='configured provider'){
 object(result,['summary','primary','related','decisions','contextCheck']);const convert=changes=>list(changes,128).map(c=>{object(c,['partId','title','kind','content','parentId','dependsOn']);return {...copy(c),before:copy(project.parts.find(p=>p.id===c.partId)??null)};});
 const proposal={id:uid(),baseRevision:project.revision,scope:copy(scope),instruction,summary:result.summary,primary:convert(result.primary),related:convert(result.related),decisions:copy(result.decisions),contextCheck:copy(result.contextCheck),model,createdAt:now(),primaryAccepted:false};return validateProposal(proposal,project);
}
export function localProposal(project,scope,instruction){
 validateScope(scope,project);if(scope.type!=='part')fail('MODEL_REQUIRED','Developing the whole intention needs a connected model. You can record parts locally, then use “Replace with:” or “Append:” in a part.',503);
 const part=project.parts.find(p=>p.id===scope.partId);const match=instruction.match(/^\s*(replace(?: this part)? with|append):\s*([\s\S]+)$/i);if(!match)fail('LOCAL_COMMAND','Local mode records exact instructions. Use “Replace with: …” or “Append: …”, or connect a server-side model.',422);
 const related=project.parts.filter(p=>p.dependsOn.includes(part.id));const content=/^append$/i.test(match[1])?`${part.content}${part.content?'\n\n':''}${match[2]}`:match[2];
 return proposalFromResult(project,scope,instruction,{summary:'Exact local replacement, ready for your review.',primary:[{partId:part.id,title:part.title,kind:part.kind,parentId:part.parentId,dependsOn:part.dependsOn,content}],related:[],decisions:[],contextCheck:{mode:'structural-only',summary:related.length?'Declared dependent parts may need attention. Their content has not been changed. Semantic whole-intention review has not run.':'The part and dependency structure were checked. Semantic whole-intention review has not run; compare this edit with your intention, constraints and acceptance.',partIds:related.map(p=>p.id)}},'local exact instruction');
}
function requireRevision(project,revision){if(revision!==project.revision)fail('STALE','A newer version exists. Reload before making another change.',409);}
export function applyCommand(input,command,revision=input.revision){
 validateProject(input);requireRevision(input,revision);if(!isObject(command)||typeof command.type!=='string')fail('SCHEMA','Invalid command.');if(input.pending&&!['acceptPrimary','acceptRelated','discard','message','discussion'].includes(command.type))fail('PENDING','Resolve the current proposal before changing the source.',409);const project=copy(input),before=sourceOf(project);let summary='',preservePending=['message','discussion'].includes(command.type)&&!!project.pending;
 const keys=(...fields)=>object(command,['type',...fields]);
 switch(command.type){
 case 'intention':keys('intention','title');text(command.intention,10000);text(command.title,120,false);project.intention=command.intention;project.title=command.title;summary='Updated the whole intention';break;
 case 'boundaries':keys('title','constraints','acceptance');text(command.title,120,false);project.title=command.title;project.constraints=copy(command.constraints);project.acceptance=copy(command.acceptance);summary='Updated constraints and acceptance';break;
 case 'addPart':keys('title','parentId','dependsOn');text(command.title,120,false);project.parts.push({id:uid(),parentId:command.parentId,title:command.title,kind:'reference',content:'',dependsOn:copy(command.dependsOn),locked:false});summary=`Recorded ${command.title}`;break;
 case 'lock':keys('partId','locked');if(typeof command.locked!=='boolean')fail('SCHEMA','Invalid lock.');{const p=project.parts.find(p=>p.id===command.partId);if(!p)fail('SCOPE','Part not found.');p.locked=command.locked;summary=`${p.locked?'Locked':'Unlocked'} ${p.title}`;}break;
 case 'decision':keys('decisionId','answer','dismiss');if(typeof command.dismiss!=='boolean')fail('SCHEMA','Invalid decision choice.');{const decision=project.decisions.find(d=>d.id===command.decisionId);if(!decision)fail('SCOPE','Decision not found.');text(command.answer,6000,command.dismiss);decision.status=command.dismiss?'dismissed':'answered';decision.answer=command.answer;summary=command.dismiss?'Set aside a decision':'Answered a material decision';}break;
 case 'message':keys('scope','text');validateScope(command.scope,project);text(command.text,6000,false);project.messages.push({id:uid(),scope:copy(command.scope),role:'user',text:command.text,at:now()});summary='Recorded a conversation note';break;
 case 'discussion':keys('scope','instruction','reply');validateScope(command.scope,project);text(command.instruction,6000,false);text(command.reply,12000,false);project.messages.push({id:uid(),scope:copy(command.scope),role:'user',text:command.instruction,at:now()},{id:uid(),scope:copy(command.scope),role:'assistant',text:command.reply,at:now()});summary='Discussed the current result';break;
 case 'propose':keys('proposal');validateProposal(command.proposal,project);project.pending=copy(command.proposal);project.messages.push({id:uid(),scope:copy(project.pending.scope),role:'user',text:project.pending.instruction,at:now()});summary='Prepared a development proposal';preservePending=true;break;
 case 'acceptPrimary':keys('proposalId');{const p=project.pending;if(!p||p.id!==command.proposalId||p.primaryAccepted)fail('PROPOSAL','No matching primary proposal remains.',409);validateProposal(p,project);applyChanges(project,p.primary);for(const decision of p.decisions){if(decision.partIds.some(v=>!project.parts.some(part=>part.id===v)))fail('SCOPE','Decisions cannot depend on unapproved related changes.');project.decisions.push({id:uid(),...copy(decision),status:'pending',answer:''});}p.primary=[];p.decisions=[];p.primaryAccepted=true;project.messages.push({id:uid(),scope:copy(p.scope),role:p.contextCheck.mode==='model'?'assistant':'local',text:p.summary,at:now()});summary='Accepted the selected development';preservePending=p.related.length>0;if(!preservePending)project.pending=null;}break;
 case 'acceptRelated':keys('proposalId');{const p=project.pending;if(!p||p.id!==command.proposalId||!p.primaryAccepted||!p.related.length)fail('PROPOSAL','Accept the primary edit before related changes.',409);validateProposal(p,project);applyChanges(project,p.related);project.pending=null;summary='Separately approved related changes';}break;
 case 'discard':keys('proposalId');if(!project.pending||project.pending.id!==command.proposalId)fail('PROPOSAL','No matching proposal remains.',409);project.pending=null;summary='Discarded unaccepted proposed changes';break;
 case 'restore':keys('historyRevision');{const event=project.history.find(h=>h.revision===command.historyRevision);if(!event?.before)fail('HISTORY','That entry has no source to restore.');Object.assign(project,copy(event.before));summary=`Restored source from before revision ${event.revision}`;}break;
 default:fail('COMMAND','Unsupported operation.');
 }
 if(!preservePending)project.pending=null;project.revision++;project.updatedAt=now();if(project.pending)project.pending.baseRevision=project.revision;
 project.history.push({revision:project.revision,at:project.updatedAt,type:command.type,summary,before:JSON.stringify(before)===JSON.stringify(sourceOf(project))?null:before});return validateProject(project);
}
export function handoff(project){validateProject(project);const lines=[`# ${project.title}`,'','## Intention',project.intention,'','## Constraints',...project.constraints.map(x=>`- ${x}`),'','## Acceptance',...project.acceptance.map(x=>`- ${x}`),'','## Structured result'];const append=(parent,depth)=>{for(const p of project.parts.filter(p=>p.parentId===parent)){lines.push('',`${'#'.repeat(Math.min(depth+3,6))} ${p.title}`,`Part: ${p.id}${p.locked?' · locked':''}${p.dependsOn.length?' · depends on '+p.dependsOn.join(', '):''}`,p.content);append(p.id,depth+1);}};append(null,0);lines.push('','## Decisions',...project.decisions.map(d=>`- [${d.status}] ${d.question}\n  Why: ${d.why}${d.answer?'\n  Answer: '+d.answer:''}`),'','## Handoff boundary',`Revision ${project.revision}. This is a project record, not evidence of execution. Pending proposals are not accepted source. No embedded AI, credentials, publication authority, or permission to expand scope is included.`);return lines.join('\n');}

/** Canonical comparison prevents equal-revision portable forks from overwriting each other. */
export function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value!==null&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value);}
export function descendsFrom(newer,older){if(newer.id!==older.id||newer.revision<older.revision)return false;if(newer.revision===older.revision)return canonical(newer)===canonical(older);const prefix=newer.history.filter(h=>h.revision<=older.revision);if(canonical(prefix)!==canonical(older.history)||canonical(newer.messages.slice(0,older.messages.length))!==canonical(older.messages))return false;let previous=sourceOf(newer);for(const h of [...newer.history].reverse())if(h.revision>older.revision&&h.before)previous=h.before;return canonical(previous)===canonical(sourceOf(older));}
