import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { authorize } from '../core/contracts.mjs';
import { validateProject, applyCommand, createProject, importProject, fail, uid } from './state.mjs';
/** Local/service persistence is authoritative; all source writes are transactional. */
export class IntentionStore {
 constructor(path=':memory:'){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);const version=this.db.prepare('PRAGMA user_version').get().user_version;if(version>1){this.db.close();fail('MIGRATION','This workspace database requires a newer application.',500);}this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS intention_projects (id TEXT NOT NULL, tenant TEXT NOT NULL, revision INTEGER NOT NULL, updated_at TEXT NOT NULL, state TEXT NOT NULL, PRIMARY KEY (tenant,id)); CREATE TABLE IF NOT EXISTS intention_proposal_owners (tenant TEXT NOT NULL, project TEXT NOT NULL, proposal TEXT NOT NULL, actor TEXT NOT NULL, PRIMARY KEY (tenant,project)); PRAGMA user_version=1;');}
 list(actor){authorize(actor,'read');return this.db.prepare('SELECT state FROM intention_projects WHERE tenant=? ORDER BY updated_at DESC').all(actor.tenant).map(row=>{const p=JSON.parse(row.state);return {id:p.id,title:p.title,intention:p.intention.slice(0,180),revision:p.revision,updatedAt:p.updatedAt};});}
 get(actor,id){authorize(actor,'read');const row=this.db.prepare('SELECT state FROM intention_projects WHERE tenant=? AND id=?').get(actor.tenant,id);if(!row)fail('NOT_FOUND','Intention not found.',404);return validateProject(JSON.parse(row.state));}
 create(actor,{intention='',title='Untitled intention',source}={}){authorize(actor,'write');const project=source?importProject(source):createProject(intention,title);if(source)project.id=uid();validateProject(project);this.db.exec('BEGIN IMMEDIATE');try{if(this.list(actor).length>=200)fail('LIMIT','This workspace already has 200 intentions.',409);this.db.prepare('INSERT INTO intention_projects VALUES(?,?,?,?,?)').run(project.id,actor.tenant,project.revision,project.updatedAt,JSON.stringify(project));if(project.pending)this.db.prepare('INSERT OR REPLACE INTO intention_proposal_owners VALUES(?,?,?,?)').run(actor.tenant,project.id,project.pending.id,actor.sub);this.db.exec('COMMIT');return project;}catch(error){this.db.exec('ROLLBACK');throw error;}}
 command(actor,id,revision,command){authorize(actor,'write');this.db.exec('BEGIN IMMEDIATE');try{const current=this.get(actor,id);if(['acceptPrimary','acceptRelated','discard'].includes(command.type)){const owner=this.db.prepare('SELECT actor,proposal FROM intention_proposal_owners WHERE tenant=? AND project=?').get(actor.tenant,id);if(!owner||owner.actor!==actor.sub||owner.proposal!==command.proposalId)fail('FORBIDDEN','Only the requesting editor can decide this proposal.',403);}const next=applyCommand(current,command,revision);const result=this.db.prepare('UPDATE intention_projects SET state=?,revision=?,updated_at=? WHERE tenant=? AND id=? AND revision=?').run(JSON.stringify(next),next.revision,next.updatedAt,actor.tenant,id,revision);if(result.changes!==1)fail('STALE','A newer version exists. Reload and try again.',409);if(command.type==='propose')this.db.prepare('INSERT OR REPLACE INTO intention_proposal_owners VALUES(?,?,?,?)').run(actor.tenant,id,next.pending.id,actor.sub);if(!next.pending)this.db.prepare('DELETE FROM intention_proposal_owners WHERE tenant=? AND project=?').run(actor.tenant,id);this.db.exec('COMMIT');return next;}catch(error){this.db.exec('ROLLBACK');throw error;}}
 close(){this.db.close();}
}
