import { test } from 'node:test';
import assert from 'node:assert/strict';
import { example, template, RECOVERY } from '../src/core/templates.mjs';
import { compile, structuralAudit, sourceHash, reviewEvidence } from '../src/core/compiler.mjs';
import { validateDocument, profiles, budget, Fault } from '../src/core/contracts.mjs';
import { importDocument } from '../src/core/importer.mjs';
const complete=()=>{const d=example();d.sections.find(s=>s.id==='recovery').content=RECOVERY;return d;};
const audit=d=>structuralAudit(d,compile(d));
test('all six domain profiles generate valid typed documents',()=>{
  for(const p of ['software','research','writing','media','operations','physical'])assert.equal(validateDocument(template('Project',[p],'Goal')).profiles[0],p);
});
test('hybrid profiles merge shared stages without duplicate IDs',()=>{const d=template('Hybrid',['software','media','operations'],'Goal');assert.equal(d.sections.filter(s=>s.kind==='recovery').length,1);validateDocument(d);});
test('profile prototype names cannot bypass validation',()=>assert.throws(()=>profiles(['__proto__']),Fault));
test('document rejects unknown writable fields',()=>assert.throws(()=>validateDocument({...example(),tenant:'escape'}),Fault));
test('document rejects duplicate section IDs',()=>{const d=example();d.sections[1].id=d.sections[0].id;assert.throws(()=>validateDocument(d),Fault);});
test('document rejects dangling dependencies',()=>{const d=example();d.sections[0].dependsOn=['missing'];assert.throws(()=>validateDocument(d),Fault);});
test('document rejects self dependency',()=>{const d=example();d.sections[0].dependsOn=['intent'];assert.throws(()=>validateDocument(d),Fault);});
test('section content limit is enforced',()=>{const d=example();d.sections[0].content='x'.repeat(30001);assert.throws(()=>validateDocument(d),Fault);});
test('compile is deterministic and does not mutate the source',()=>{const d=complete(),before=structuredClone(d);assert.deepEqual(compile(d),compile(d));assert.deepEqual(d,before);});
test('every normative section is preserved exactly and source-mapped',()=>{const d=complete(),c=compile(d),lines=c.content.split('\n');for(const s of d.sections){const map=c.sourceMap.find(m=>m.sectionId===s.id);assert.equal(lines.slice(map.startLine-1,map.endLine).join('\n'),s.content);}});
test('locked decisions survive compilation intact',()=>{const d=complete();assert.ok(compile(d).content.includes(d.sections.find(s=>s.locked).content));});
test('all target adapters preserve identical source',()=>{const d=complete();for(const target of ['codex','antigravity','generic'])for(const s of d.sections)assert.ok(compile(d,{target}).content.includes(s.content));});
test('unknown and prototype targets fail closed',()=>{assert.throws(()=>compile(complete(),{target:'__proto__'}),Fault);assert.throws(()=>compile(complete(),{target:'imaginary'}),Fault);});
test('context overflow does not truncate source',()=>{const d=complete(),c=compile(d,{budget:{context:2048,reserve:1024}});assert.equal(c.budget.fits,false);assert.ok(c.content.includes(d.sections.at(-1).content));assert.ok(structuralAudit(d,c).findings.some(f=>f.code==='CONTEXT_OVERFLOW'));});
test('invalid reserve is rejected instead of producing negative capacity',()=>{for(const b of [{context:1000,reserve:2000},{context:10000,reserve:10000},{context:4000,reserve:0},{context:NaN,reserve:2000}])assert.throws(()=>budget(b),Fault);});
test('changing source invalidates the source hash',()=>{const d=complete(),hash=sourceHash(d);d.sections[0].content+=' New.';assert.notEqual(sourceHash(d),hash);});
test('example has a real unresolved recovery blocker',()=>{assert.ok(audit(example()).findings.some(f=>f.code==='UNRESOLVED'&&f.sectionIds.includes('recovery')));});
test('completed example passes structural checks without semantic claims',()=>{const a=audit(complete());assert.equal(a.findings.filter(f=>f.severity==='blocker').length,0);assert.match(a.scope,/not semantic completeness/);});
test('empty source is flagged rather than filled silently',()=>{const d=complete();d.sections[0].content='';const a=audit(d);assert.ok(a.findings.some(f=>f.code==='EMPTY_SECTION'));assert.equal(d.sections[0].content,'');});
test('missing domain stage blocks publish readiness',()=>{const d=complete();d.sections=d.sections.filter(s=>s.kind!=='security');assert.ok(audit(d).findings.some(f=>f.code==='MISSING_STAGE'));});
test('unproven requirement is found',()=>{const d=complete();d.sections.find(s=>s.kind==='requirements').content+='\nREQ-99: No empty output.';assert.ok(audit(d).findings.some(f=>f.code==='UNPROVEN_REQUIREMENT'&&f.message.includes('REQ-99')));});
test('REQ-010 does not count as REQ-01 coverage',()=>{const d=complete();d.sections.find(s=>s.kind==='verification').content=d.sections.find(s=>s.kind==='verification').content.replace('REQ-01:','REQ-010:');assert.ok(audit(d).findings.some(f=>f.code==='UNPROVEN_REQUIREMENT'));});
test('verification without a requirement is an orphan warning',()=>{const d=complete();d.sections.find(s=>s.kind==='verification').content+='\nREQ-99: Check irrelevant work.';assert.ok(audit(d).findings.some(f=>f.code==='ORPHAN_TEST'));});
test('exact duplicate is reported, not silently discarded',()=>{const d=complete();d.sections[1].content=d.sections[0].content;assert.ok(audit(d).findings.some(f=>f.code==='DUPLICATE'));assert.ok(compile(d).sourceMap.some(s=>s.sectionId===d.sections[1].id));});
test('explicit conflicting decisions block compilation readiness',()=>{const d=complete();d.sections[0].content+='\n@decision manual-editing = forbidden';d.sections[1].content+='\n@decision manual-editing = permitted';assert.ok(audit(d).findings.some(f=>f.code==='DECISION_CONFLICT'));});
test('dependency cycles are detected',()=>{const d=complete();d.sections[0].dependsOn=[d.sections[1].id];assert.ok(audit(d).findings.some(f=>f.code==='DEPENDENCY_CYCLE'));});
test('review requires literal provenance',()=>{const d=complete(),raw={coveredSectionIds:d.sections.map(s=>s.id),findings:[{severity:'warning',message:'A risk',sectionIds:['intent'],quote:'Invented quote'}]};assert.throws(()=>reviewEvidence(raw,d,'semantic'),Fault);});
test('review requires coverage of every section',()=>assert.throws(()=>reviewEvidence({findings:[],coveredSectionIds:['intent']},complete(),'semantic'),Fault));
test('review rejects fabricated section identities',()=>{const d=complete();assert.throws(()=>reviewEvidence({findings:[],coveredSectionIds:[...d.sections.map(s=>s.id),'fake']},d,'semantic'),Fault);});
test('review accepts evidenced warnings but never edits source',()=>{const d=complete(),before=structuredClone(d);const f=reviewEvidence({coveredSectionIds:d.sections.map(s=>s.id),findings:[{severity:'warning',message:'Check the intended outcome.',sectionIds:['intent'],quote:'Make the document'}]},d,'semantic');assert.equal(f[0].origin,'semantic');assert.deepEqual(d,before);});
test('source backup round-trip preserves sections, resets identity and trust',()=>{const d=complete(),imported=importDocument(JSON.stringify(d));assert.notEqual(imported.id,d.id);assert.equal(imported.revision,1);assert.deepEqual(imported.sections,d.sections);});
test('Markdown import preserves source as untrusted text',()=>{const d=importDocument('# Intent\n<script>alert(1)</script>\n\n## Constraints\nNever lose content.');assert.equal(d.sections[0].content,'<script>alert(1)</script>');assert.equal(d.sections[1].kind,'constraints');});
test('malformed backup returns a user-correctable error',()=>assert.throws(()=>importDocument('{broken'),e=>e.code==='IMPORT_JSON'&&e.status===400));

for(const value of [undefined,null,12,{},[]])test(`section IDs reject non-string ${JSON.stringify(value)}`,()=>{
 const d=example();d.sections[0].id=value;assert.throws(()=>validateDocument(d));
});
test('profile values cannot be arrays coerced to known names',()=>assert.throws(()=>profiles([['software']])));
test('timestamps are required and must be parseable',()=>{const d=example();delete d.createdAt;assert.throws(()=>validateDocument(d));d.createdAt='not a date';assert.throws(()=>validateDocument(d));});
