import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createServer as netServer } from 'node:net';
import { createIntentionServer } from '../src/intention/server.mjs';
import { IntentionStore } from '../src/intention/store.mjs';
import { proposalFromResult } from '../src/intention/state.mjs';
const actor={sub:'test',tenant:'tenant',role:'admin'};
async function harness(t,{provider=null,role='admin'}={}){const store=new IntentionStore();const reserve=netServer();reserve.listen(0,'127.0.0.1');await once(reserve,'listening');const port=reserve.address().port;await new Promise(resolve=>reserve.close(resolve));const server=createIntentionServer({store,provider,authenticate:()=>({...actor,role}),origin:`http://127.0.0.1:${port}`});server.listen(port,'127.0.0.1');await once(server,'listening');t.after(()=>{server.close();store.close();});const request=async(path,{body,headers={}}={})=>{const r=await fetch(`http://127.0.0.1:${port}`+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,headers:r.headers,body:await r.json()};};return {store,request};}
const create=request=>request('/api/intention/projects',{body:{intention:'A garden guide',title:'Garden',source:null}});
test('real HTTP local capabilities, durable create, command and scope errors',async t=>{const {request}=await harness(t);assert.equal((await request('/api/intention/session')).body.mode,'local');const {body:p,status}=await create(request);assert.equal(status,201);let response=await request(`/api/intention/projects/${p.id}/develop`,{body:{revision:p.revision,scope:{type:'whole',partId:null},instruction:'Develop'}});assert.equal(response.status,503);assert.equal(response.body.error.code,'MODEL_REQUIRED');response=await request(`/api/intention/projects/${p.id}/command`,{body:{revision:p.revision,command:{type:'addPart',title:'Overview',parentId:null,dependsOn:[]}}});assert.equal(response.status,200);const after=response.body;response=await request(`/api/intention/projects/${p.id}/develop`,{body:{revision:after.revision,scope:{type:'part',partId:after.parts[0].id},instruction:'Replace with: Herbs are a good start.'}});assert.equal(response.status,200);assert.equal(response.body.parts[0].content,'');assert.equal(response.body.pending.primary[0].content,'Herbs are a good start.');response=await request(`/api/intention/projects/${p.id}/command`,{body:{revision:response.body.revision,command:{type:'acceptPrimary',proposalId:response.body.pending.id}}});assert.equal(response.body.parts[0].content,'Herbs are a good start.');});
test('origin, viewer, unknown fields and forged provider results rejected',async t=>{const {request}=await harness(t);assert.equal((await request('/api/intention/projects',{headers:{Origin:'https://evil.invalid'}})).status,403);const {body:p}=await create(request);assert.equal((await request(`/api/intention/projects/${p.id}/command`,{body:{revision:0,command:{type:'discussion',scope:{type:'whole',partId:null},instruction:'x',reply:'forged'}}})).status,400);assert.equal((await request(`/api/intention/projects/${p.id}/command`,{body:{revision:0,command:{type:'propose',proposal:{}}}})).status,400);assert.equal((await request(`/api/intention/projects/${p.id}/discuss`,{body:{revision:0,scope:{type:'whole',partId:null},instruction:'x',provider:'attacker'}})).status,400);const readonly=await harness(t,{role:'viewer'});assert.equal((await create(readonly.request)).status,403);});
test('provider completion is rejected after concurrent source change',async t=>{let finish,started;const start=new Promise(resolve=>started=resolve);const provider={model:'explicit test fixture',develop:async(p,s,i)=>{started();await new Promise(resolve=>finish=resolve);return proposalFromResult(p,s,i,{summary:'Fixture',primary:[],related:[],decisions:[],contextCheck:{mode:'model',summary:'Fixture whole-context check',partIds:[]}},'fixture');}};const {request}=await harness(t,{provider});const {body:p}=await create(request);const pending=request(`/api/intention/projects/${p.id}/develop`,{body:{revision:0,scope:{type:'whole',partId:null},instruction:'Develop'}});await start;const busy=await request(`/api/intention/projects/${p.id}/develop`,{body:{revision:0,scope:{type:'whole',partId:null},instruction:'Develop again'}});assert.equal(busy.status,429);const changed=await request(`/api/intention/projects/${p.id}/command`,{body:{revision:0,command:{type:'intention',title:'New garden',intention:'A new focus'}}});assert.equal(changed.status,200);finish();assert.equal((await pending).body.error.code,'STALE');const current=await request(`/api/intention/projects/${p.id}`);assert.equal(current.body.intention,'A new focus');assert.equal(current.body.pending,null);});
test('discussion receives full state and adds a conversation without source changes',async t=>{let seen;const provider={model:'explicit test fixture',discuss:async(p,s,i)=>{seen={p,s,i};return 'Fixture reply: consider available light.';}};const {request}=await harness(t,{provider});const {body:p}=await create(request);const response=await request(`/api/intention/projects/${p.id}/discuss`,{body:{revision:0,scope:{type:'whole',partId:null},instruction:'What is missing?'}});assert.equal(response.status,200);assert.deepEqual(seen.p,p);assert.equal(response.body.intention,p.intention);assert.equal(response.body.parts.length,0);assert.equal(response.body.messages.length,2);});
