/** Browser-test fixture. Never imported by the production application. */
import { createIntentionServer } from '../src/intention/server.mjs';
import { IntentionStore } from '../src/intention/store.mjs';
import { proposalFromResult } from '../src/intention/state.mjs';
const origin=`http://127.0.0.1:${process.env.PORT}`;
const provider={model:'explicit browser test fixture',async develop(project,scope,instruction){
 if(instruction==='provider failure')throw Object.assign(new Error('The test provider failed. Your accepted work is unchanged.'),{status:502,code:'FIXTURE_FAILURE'});
 const change=(part,content)=>({partId:part.id,parentId:part.parentId,title:part.title,kind:part.kind,dependsOn:part.dependsOn,content});
 let result;if(scope.type==='whole'){result={summary:'A useful guide, with one material choice to make.',primary:[{partId:'overview',parentId:null,title:'The small garden',kind:'outcome',content:'Grow something good, one small step at a time. This guide helps a first-time gardener choose an easy starting point and learn by caring for it.',dependsOn:[]},{partId:'steps',parentId:null,title:'From seed to first harvest',kind:'execution',content:'Choose a container with drainage. Find a spot with morning light. Start with basil or salad leaves, check the soil each day, and water when its surface feels dry.',dependsOn:['overview']},{partId:'detail',parentId:'steps',title:'The first week',kind:'reference',content:'Day one: prepare the pot and plant. Each morning: notice the light and the soil. At the end of the week: record what changed.',dependsOn:[]}],related:[],decisions:[{question:'Will this garden be indoors or outside?',why:'The location changes the light, watering and plant choices.',partIds:['overview','steps']}],contextCheck:{mode:'model',summary:'Fixture assessment: the guide preserves the no-pesticide constraint and beginner-friendly acceptance.',partIds:project.parts.map(p=>p.id)}};}else{const selected=project.parts.find(p=>p.id===scope.partId),other=project.parts.find(p=>p.id!==selected.id&&p.parentId===null);result={summary:'Make the starting point a balcony herb garden.',primary:[change(selected,'A balcony herb garden for first-time growers. Begin with basil and mint, and enjoy the small daily habit of caring for them.')],related:other?[change(other,'Choose balcony-safe containers with drainage. Start basil and mint in separate pots. Water according to the soil, not a fixed schedule.')]:[],decisions:[],contextCheck:{mode:'model',summary:'The overview now names balcony herbs. The growing steps need a related update, which remains separate until you approve it.',partIds:other?[other.id]:[]}};}
 return proposalFromResult(project,scope,instruction,result,this.model);
},async discuss(project,scope,instruction){return `Fixture discussion at ${scope.type} scope: the intention is “${project.intention}”. There are ${project.parts.length} parts. No source was changed.`;}};
const store=new IntentionStore(process.env.INTENTION_DB??':memory:');const server=createIntentionServer({store,provider,authenticate:()=>({sub:'fixture',tenant:'fixture',role:'admin'}),origin});server.listen(Number(process.env.PORT),'127.0.0.1',()=>console.log('Browser fixture listening '+origin));
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>server.close(()=>{store.close();process.exit(0);}));
