import { esc, icon, markdown, shortHash, number, date } from './presentation.mjs';
const STYLE=new URL('./document.css',import.meta.url).href;
const LOGO=new URL('./document.svg',import.meta.url).href;
const UNIVERSAL=['intent','outcome','audience','deliverables','requirements','constraints','structure','execution','verification','delivery'];
const NAMES={intent:'Intent',outcome:'Outcome',audience:'Audience',deliverables:'Deliverables',requirements:'Requirements',constraints:'Constraints',structure:'Structure',execution:'Execution',verification:'Verification',delivery:'Delivery',interaction:'Interaction',data:'Data',recovery:'Recovery',security:'Security',method:'Method',evidence:'Evidence',alternatives:'Alternatives',voice:'Voice',continuity:'Continuity',direction:'Direction',assets:'Assets',operations:'Operations',economics:'Economics',materials:'Materials',safety:'Safety',reference:'Reference'};
const KINDS=Object.keys(NAMES);
const btn=(action,label,glyph='',cls='quiet',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${glyph?icon(glyph):''}${label}</button>`;
export const DOCUMENT_MANIFEST=Object.freeze({id:'language-canvas.document',label:'Document',kind:'document',version:'1.0.0',customElement:'language-document',acceptedImports:['text/markdown','text/plain','application/json'],exports:['BUILD.md','BUILD.txt'],nativeSpacesIntegration:false});
/** Embeddable host module. configure() may be called before or after mounting. */
export class DocumentModule extends HTMLElement {
  constructor(){
    super();this.root=this.attachShadow({mode:'open'});this.options={apiBase:'/api'};
    this.s={docs:[],doc:null,session:null,selected:null,mode:'draft',sidebar:matchMedia('(min-width:1180px)').matches,menu:false,busy:false,error:null,notice:'',proposal:null,audit:null,release:null,instructions:{},target:'codex',context:128000,reserve:32000,format:'md',semantic:false,ack:false,dialog:null,history:null,theme:'dark'};
    this.root.addEventListener('click',e=>this.click(e));this.root.addEventListener('keydown',e=>this.key(e));
    this.root.addEventListener('input',e=>this.input(e));this.root.addEventListener('change',e=>this.change(e));
  }
  configure(options){this.options={...this.options,...options};if(this.isConnected)this.load();return this;}
  connectedCallback(){this.load();}
  async api(path,method='GET',data){
    const token=await this.options.getAccessToken?.();const headers={};if(token)headers.Authorization=`Bearer ${token}`;if(data!==undefined)headers['Content-Type']='application/json';
    const response=await fetch(`${this.options.apiBase}${path}`,{method,headers,body:data===undefined?undefined:JSON.stringify(data),credentials:'same-origin'});
    if(!response.ok){let error;try{error=(await response.json()).error;}catch{error={code:'CONNECTION',message:'The server returned an unreadable response.'};}throw Object.assign(new Error(error.message),{code:error.code});}
    return response.headers.get('content-type')?.includes('application/json')?response.json():response.text();
  }
  async load(){
    this.s.busy=true;this.render();
    try{
      this.s.session=await this.api('/session');this.s.semantic=false;this.s.docs=await this.api('/documents');
      if(!this.s.docs.length&&this.s.session.local){const d=await this.api('/documents','POST',{type:'example'});this.s.docs=[d];}
      const id=this.options.documentId??this.s.doc?.id??this.s.docs[0]?.id;
      if(id){this.s.doc=await this.api(`/documents/${id}`);this.s.selected=this.s.doc.sections[0]?.id;}
      this.s.error=null;
    }catch(e){this.s.error={message:e.message,code:e.code};}
    this.s.busy=false;this.render();
  }
  get section(){return this.s.doc?.sections.find(s=>s.id===this.s.selected);}
  get canWrite(){return ['editor','publisher','admin'].includes(this.s.session?.actor.role);}
  get canPublish(){return ['publisher','admin'].includes(this.s.session?.actor.role);}
  async run(fn){if(this.s.busy)return;this.s.busy=true;this.s.error=null;this.render();try{await fn();}catch(e){this.s.error={message:e.message,code:e.code};}finally{this.s.busy=false;this.render();}}
  async updated(doc){this.s.doc=doc;this.s.audit=null;this.s.release=null;this.s.docs=await this.api('/documents');this.dispatchEvent(new CustomEvent('document-changed',{detail:{documentId:doc.id,revision:doc.revision},bubbles:true,composed:true}));}
  select(id){
    if(this.s.busy)return;
    if(this.s.proposal&&this.s.proposal.sectionId!==id){this.s.notice='Accept or discard your pending proposal before selecting another section.';this.render();return;}
    this.s.selected=id;this.s.mode='draft';this.s.menu=false;this.s.notice='';this.render();
    this.root.querySelector(`[data-section="${CSS.escape(id)}"]`)?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
  }
  async click(e){
    const actionEl=e.target.closest('[data-action]'),sectionEl=e.target.closest('[data-section]');
    if(!actionEl&&sectionEl){this.select(sectionEl.dataset.section);return;}
    if(!actionEl)return;const action=actionEl.dataset.action;if(this.s.busy&&!['about','connection','close-notice','toggle-sidebar'].includes(action))return;
    if(action==='toggle-sidebar'){this.s.sidebar=!this.s.sidebar;this.render();return;}
    if(action==='new-menu'){this.s.menu=!this.s.menu;this.render();if(this.s.menu)this.root.querySelector('[role="menu"] button:not(:disabled)')?.focus();return;}
    if(action==='new'){this.s.menu=false;this.openDialog('create');return;}
    if(action==='about'){this.openDialog('about');return;}
    if(action==='connection'){this.openDialog('connection');return;}
    if(action==='theme'){this.s.theme=this.s.theme==='dark'?'light':'dark';this.render();return;}
    if(action==='close-dialog'){this.closeDialog();return;}
    if(action==='close-notice'){this.s.notice='';this.s.error=null;this.render();return;}
    if(action==='profile-dialog'){this.openDialog('profiles');return;}
    if(action==='add-section'){this.openDialog('section');return;}
    if(action==='load-doc'){await this.run(async()=>{if(this.s.proposal)throw new Error('Accept or discard the pending proposal first.');this.s.doc=await this.api(`/documents/${actionEl.dataset.id}`);this.s.selected=this.s.doc.sections[0]?.id;this.s.audit=null;this.s.release=null;this.s.mode='draft';});return;}
    if(action==='select'){this.select(actionEl.dataset.id);return;}
    if(action==='draft'){this.s.mode='draft';this.s.notice='';this.render();return;}
    if(action==='publish-view'){
      if(this.s.proposal){this.s.notice='Accept or discard the pending proposal before compiling.';this.render();return;}
      this.s.mode='publish';this.s.notice='';this.render();if(!this.s.audit)await this.audit();return;
    }
    if(action==='suggest'){if(this.section){this.s.instructions[this.section.id]=actionEl.dataset.text;this.render();this.root.querySelector('#instruction')?.focus();}return;}
    if(action==='propose'){await this.run(async()=>{
      const instruction=(this.s.instructions[this.section.id]??'').trim();if(!instruction)throw new Error('Describe what should change first.');
      this.s.proposal=await this.api(`/documents/${this.s.doc.id}/proposals`,'POST',{sectionId:this.section.id,instruction,revision:this.s.doc.revision});
    });this.root.querySelector('[data-action="accept"]')?.focus();return;}
    if(action==='accept'){await this.run(async()=>{const doc=await this.api(`/documents/${this.s.doc.id}/accept`,'POST',{proposalId:this.s.proposal.id});this.s.proposal=null;await this.updated(doc);this.s.notice='One section updated. Everything else stayed exactly as it was.';});return;}
    if(action==='discard'){this.s.proposal=null;this.s.notice='Proposal discarded. Your accepted document is unchanged.';this.render();this.root.querySelector('#instruction')?.focus();return;}
    if(action==='lock'){await this.run(async()=>{await this.updated(await this.api(`/documents/${this.s.doc.id}/lock`,'POST',{sectionId:this.section.id,revision:this.s.doc.revision,locked:!this.section.locked}));});return;}
    if(action==='undo'){await this.run(async()=>{await this.updated(await this.api(`/documents/${this.s.doc.id}/undo`,'POST',{sectionId:this.section.id,revision:this.s.doc.revision}));this.s.proposal=null;this.s.notice='Previous content restored for this section only. History is preserved.';});return;}
    if(action==='refresh'){await this.run(async()=>{if(this.s.doc){this.s.doc=await this.api(`/documents/${this.s.doc.id}`);this.s.proposal=null;this.s.audit=null;this.s.notice='Latest revision loaded. Your instruction is still here.';}else await this.load();});return;}
    if(action==='history'){this.dialogReturn='[data-action="history"]';await this.run(async()=>{this.s.history=await this.api(`/documents/${this.s.doc.id}/history`);this.s.dialog='history';});return;}
    if(action==='backup'){await this.run(async()=>this.download(JSON.stringify(await this.api(`/documents/${this.s.doc.id}/backup`),null,2),'document.canvas.json','application/json'));return;}
    if(action==='audit'){await this.audit();return;}
    if(action==='export'){await this.run(async()=>{const content=await this.api(`/documents/${this.s.doc.id}/export`,'POST',{auditId:this.s.audit.id,format:this.s.format});this.download(content,`BUILD-DRAFT.${this.s.format}`);this.s.notice='Draft exported with its audit limitations. No release was implied.';});return;}
    if(action==='publish'){await this.run(async()=>{
      this.s.release=await this.api(`/documents/${this.s.doc.id}/publish`,'POST',{auditId:this.s.audit.id,acknowledged:this.s.ack?this.s.audit.findings.filter(f=>f.severity==='warning').map(f=>f.id):[]});
      this.download(this.s.release.content,`BUILD.${this.s.format}`);this.s.notice='Audited source snapshot published. Implementation still requires its own verification.';
      this.dispatchEvent(new CustomEvent('document-published',{detail:{documentId:this.s.doc.id,releaseId:this.s.release.id,revision:this.s.release.revision},bubbles:true,composed:true}));
    });return;}
    if(action==='create-submit'){
      const title=this.root.querySelector('#new-title').value.trim(),goal=this.root.querySelector('#new-goal').value.trim(),profile=this.root.querySelector('#new-profile').value;
      if(!title||!goal){this.root.querySelector('#create-error').textContent='Give the document a name and a starting idea.';return;}
      this.closeDialog();await this.run(async()=>{const d=await this.api('/documents','POST',{type:'brief',title,goal,profiles:[profile]});await this.updated(d);this.s.selected=d.sections[0].id;this.s.mode='draft';this.s.notice=this.s.session.provider==='rehearsal'?'Created a typed starting canvas. Empty stages stay visible as audit gaps.':'Created a draft. Audit it before using it as a build contract.';});return;
    }
    if(action==='example'){this.closeDialog();await this.run(async()=>{const d=await this.api('/documents','POST',{type:'example'});await this.updated(d);this.s.selected=d.sections[0].id;this.s.mode='draft';});return;}
    if(action==='import'){this.root.querySelector('#import-file')?.click();return;}
    if(action==='profiles-save'){
      const selected=[...this.root.querySelectorAll('input[name="profile"]:checked')].map(x=>x.value);
      if(!selected.length){this.root.querySelector('#profile-error').textContent='Keep at least one project profile.';return;}
      this.closeDialog();await this.run(async()=>{await this.updated(await this.api(`/documents/${this.s.doc.id}/profiles`,'POST',{profiles:selected,revision:this.s.doc.revision}));this.s.notice='Spine updated. Existing source was preserved; new required stages are empty until authored.';});return;
    }
    if(action==='section-save'){
      const title=this.root.querySelector('#section-title').value.trim(),kind=this.root.querySelector('#section-kind').value;
      if(!title){this.root.querySelector('#section-error').textContent='Name the new section.';return;}
      this.closeDialog();await this.run(async()=>{const d=await this.api(`/documents/${this.s.doc.id}/sections`,'POST',{title,kind,revision:this.s.doc.revision});await this.updated(d);this.s.selected=d.sections.at(-1).id;this.s.mode='draft';});return;
    }
  }
  input(e){if(e.target.id==='instruction'&&this.section)this.s.instructions[this.section.id]=e.target.value;}
  async change(e){
    if(['target','context','reserve'].includes(e.target.id)){this.s[e.target.id]=e.target.id==='target'?e.target.value:Number(e.target.value);this.s.audit=null;this.s.release=null;this.render();return;}
    if(e.target.id==='format'){this.s.format=e.target.value;this.render();return;}
    if(e.target.id==='semantic'){this.s.semantic=e.target.checked;return;}
    if(e.target.id==='ack'){this.s.ack=e.target.checked;this.render();return;}
    if(e.target.id==='import-file'){
      const file=e.target.files?.[0];if(!file)return;
      if(file.size>900000){this.s.error={message:'The import exceeds 900 KB.'};this.render();return;}
      await this.run(async()=>{const d=await this.api('/documents','POST',{type:'import',source:await file.text(),title:file.name.replace(/\.[^.]+$/,'').slice(0,120),profiles:['writing']});await this.updated(d);this.s.selected=d.sections[0].id;this.s.mode='draft';this.s.notice='Imported as new, unaudited source. Original documents were not overwritten.';});
    }
  }
  key(e){
    if(e.key==='Escape'){
      if(this.s.dialog){e.preventDefault();this.closeDialog();return;}
      if(this.s.menu){this.s.menu=false;this.render();this.root.querySelector('[data-action="new-menu"]')?.focus();return;}
    }
    if(e.target.id==='instruction'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();this.root.querySelector('[data-action="propose"]')?.click();return;}
    if(e.target.matches('[data-section]')){
      if(['Enter',' '].includes(e.key)){e.preventDefault();this.select(e.target.dataset.section);this.root.querySelector('#instruction')?.focus();}
      if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const list=[...this.root.querySelectorAll('[data-section]')],i=list.indexOf(e.target);list[(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus();}
    }
    if(e.target.closest('[role="menu"]')&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const list=[...this.root.querySelectorAll('[role="menu"] button:not(:disabled)')],i=list.indexOf(e.target);list[(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus();}
  }
  async audit(){await this.run(async()=>{
    this.s.audit=await this.api(`/documents/${this.s.doc.id}/audit`,'POST',{revision:this.s.doc.revision,target:this.s.target,budget:{context:this.s.context,reserve:this.s.reserve},semantic:this.s.semantic});this.s.ack=false;
  });}
  openDialog(type){
    const active=this.root.activeElement;
    this.dialogReturn=active?.id?`#${CSS.escape(active.id)}`:active?.dataset.action?`[data-action="${CSS.escape(active.dataset.action)}"]`:'[data-action="new-menu"]';
    this.s.dialog=type;this.render();
  }
  closeDialog(){
    this.s.dialog=null;this.s.menu=false;this.root.querySelector('dialog')?.close();this.render();
    (this.root.querySelector(this.dialogReturn??'[data-action="new-menu"]')??this.root.querySelector('#workspace'))?.focus({preventScroll:true});
  }
  download(content,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  rail(){return `<nav class="rail" aria-label="Reference host controls">${btn('toggle-sidebar','', 'home','rail-button','aria-label="Toggle workspace sidebar"')}${btn('toggle-sidebar','','space','rail-button active','aria-label="Space sidebar"')}${btn('history','','clock','rail-button',`aria-label="Document history" ${this.s.doc?'':'disabled'}`)}<span class="rail-spacer"></span>${btn('theme','','moon','rail-button','aria-label="Toggle light or dark theme"')}${btn('about','LC','','avatar','aria-label="About Language Canvas"')}</nav>`;}
  sidebar(){
    const s=this.s;
    return `<aside class="sidebar" aria-label="Space"><div class="space-heading"><h2>Space</h2>${btn('connection','','bell','icon-button','aria-label="Connection status"')}${btn('toggle-sidebar','','panel','icon-button','aria-label="Close sidebar"')}</div>
    <div class="new-wrap">${btn('new-menu','New','plus','new-button',`aria-haspopup="menu" aria-expanded="${s.menu}" ${!this.canWrite?'disabled':''}`)}
    ${s.menu?`<div class="create-menu" role="menu" aria-label="Create new"><p>Create new</p><button role="menuitem" disabled title="Provided by the host, not this module">${icon('document')}Page</button><button role="menuitem" data-action="new" class="document-menu">${icon('file')}<span>Document</span><span class="new-tag">New</span></button><button role="menuitem" disabled>${icon('slides')}Slides <span>Coming soon</span></button><button role="menuitem" disabled>${icon('sheet')}Sheet <span>Coming soon</span></button><button role="menuitem" disabled>${icon('grid')}Site</button><button role="menuitem" disabled>${icon('image')}Image</button><hr><button role="menuitem" data-action="import">${icon('upload')}Upload text file</button><button role="menuitem" data-action="example">${icon('grid')}Start from example</button><small>Reference shell · other types belong to the host</small></div>`:''}</div>
    <div class="sidebar-label">Your documents <span>${s.docs.length}</span></div><nav class="document-nav" aria-label="Documents">${s.docs.map(d=>`<button data-action="load-doc" data-id="${esc(d.id)}" class="document-link ${s.doc?.id===d.id?'current':''}" ${s.doc?.id===d.id?'aria-current="page"':''}>${icon('document')}<span>${esc(d.title)}</span></button>`).join('')}</nav>
    <div class="sidebar-label outline-heading">In this document</div><nav class="outline" aria-label="Document outline">${s.doc?.sections.map((section,i)=>`<button data-action="select" data-id="${esc(section.id)}" class="${s.selected===section.id?'current':''}"><span>${String(i+1).padStart(2,'0')}</span><span>${esc(section.title)}</span>${section.locked?icon('lock'):''}</button>`).join('')??''}</nav>
    <div class="workspace-footer"><span class="workspace-mark">${icon('space')}</span><div><strong>${s.session?.local?'Local workspace':'Host workspace'}</strong><span>${s.session?.provider==='rehearsal'?'Rehearsal · no API calls':'Connected model'}</span></div>${btn('connection','','info','icon-button','aria-label="Workspace details"')}</div></aside>`;
  }
  toolbar(){const s=this.s;return `<header class="toolbar"><div class="breadcrumbs">${btn('toggle-sidebar','','panel','icon-button','aria-label="Show or hide sidebar"')}<span>Space</span>${icon('chevron')}<span class="breadcrumb-type">Document</span></div><div class="mode-switch" role="group" aria-label="Document mode">${btn('draft','Draft','','mode-button '+(s.mode==='draft'?'selected':''),`aria-pressed="${s.mode==='draft'}"`)}${btn('publish-view','Publish','','mode-button '+(s.mode==='publish'?'selected':''),`aria-pressed="${s.mode==='publish'}"`)}</div><div class="toolbar-right"><span class="saved">${icon('check')}<span>Saved · r${s.doc?.revision??1}</span></span>${btn('history','','clock','icon-button','aria-label="View history"')}${btn('backup','','download','icon-button','aria-label="Back up source"')}</div></header>`;}
  draft(){const s=this.s,d=s.doc,selected=this.section;return `<div class="draft-layout"><div class="draft-column"><main class="document-scroll" aria-label="Draft canvas"><div class="document-heading"><div class="eyebrow">${icon('document')}DOCUMENT <span>/</span> LANGUAGE CANVAS</div><h1>${esc(d.title)}</h1><p class="document-subtitle">Click defines scope. Language defines change.</p><div class="doc-meta"><span>${d.sections.length} sections</span><span>·</span><button data-action="profile-dialog">${d.profiles.map(p=>esc(s.session.profiles[p]?.label.split(' & ')[0]??p)).join(' + ')} ${icon('down')}</button><span class="meta-spacer"></span><span>${icon('lock')}Protected by scope</span></div></div>
    <div class="sections">${d.sections.map((section,i)=>`<section data-section="${esc(section.id)}" role="button" tabindex="${s.selected===section.id?'0':'-1'}" aria-label="Select ${esc(section.title)} section" aria-pressed="${s.selected===section.id}" aria-describedby="section-content-${esc(section.id)}" class="canvas-section ${s.selected===section.id?'is-selected':''} ${section.locked?'is-locked':''}"><div class="section-kicker"><span>${String(i+1).padStart(2,'0')} <span class="kind-label">${esc(NAMES[section.kind])}</span></span><span class="selection-label">${s.selected===section.id?`${icon('check')}Selected`:section.locked?`${icon('lock')}Locked`:''}</span></div><h2>${esc(section.title)}</h2><div class="section-content" id="section-content-${esc(section.id)}">${section.content?markdown(section.content):'<p class="empty-section">This part of the idea is still open. Select it and describe what belongs here.</p>'}</div></section>`).join('')}</div>
    ${btn('add-section','Add a section','plus','add-section',`${!this.canWrite?'disabled':''}`)}<div class="canvas-end">The document is the work. Not a transcript of it.</div></main>
    ${s.proposal?this.proposal():this.composer(selected)}</div>${this.inspector()}</div>`;}
  composer(selected){const s=this.s;return `<div class="composer" aria-label="Section instruction"><div class="composer-label"><span>${icon(selected?.locked?'lock':'document')}<label for="instruction">Change <strong>${esc(selected?.title??'a section')}</strong></label></span><span class="composer-tools">${btn('undo','','undo','icon-button',`aria-label="Restore selected section" ${this.canWrite&&!selected?.locked&&!s.busy?'':'disabled'}`)}${btn('lock','',selected?.locked?'unlock':'lock','icon-button',`aria-label="${selected?.locked?'Unlock':'Lock'} selected section" ${this.canWrite&&!s.busy?'':'disabled'}`)}<span class="scope-tag">Only this section</span></span></div><div class="instruction-row"><textarea id="instruction" rows="2" maxlength="6000" placeholder="${selected?.locked?'This decision is locked. Unlock it to propose a change.':'Describe what should change…'}" ${s.busy||selected?.locked||!this.canWrite?'disabled':''}>${esc(s.instructions[selected?.id]??'')}</textarea>${btn('propose','','arrow','send-button',`aria-label="Propose section change" ${s.busy||selected?.locked||!this.canWrite?'disabled':''}`)}</div><div class="composer-bottom"><span>${s.busy?'<span class="spinner"></span> Working. Accepted source is unchanged.':s.session.provider==='rehearsal'?'Rehearsal · deterministic instructions':'Connected model · metered API usage'}</span><span>Enter to propose <span class="keyboard-hint">↵</span></span></div></div>`;}
  proposal(){const p=this.s.proposal;return `<div class="proposal-panel" role="region" aria-label="Proposed section change"><div class="proposal-heading"><div><span class="eyebrow">REVIEW CHANGE</span><h3>One section. Nothing else.</h3></div><span class="scope-tag">r${p.revision} → r${p.revision+1}</span></div><div class="diff"><div><span class="diff-label">BEFORE</span><div class="before">${markdown(p.before)}</div></div><div><span class="diff-label">PROPOSED</span><div class="after">${markdown(p.after)}</div></div></div><div class="proposal-actions"><span>${esc(this.s.session.provider==='rehearsal'?'Rehearsal proposal · not model output':p.model)}</span>${btn('discard','Discard','','quiet')}${btn('accept','Accept change','check','primary',this.s.busy?'disabled':'')}</div></div>`;}
  inspector(){const s=this.s,section=this.section,d=s.doc;const filled=UNIVERSAL.filter(k=>d.sections.some(x=>x.kind===k&&x.content.trim())).length;return `<aside class="inspector" aria-label="Document spine"><div class="inspector-heading"><h2>Document spine</h2>${icon('link')}</div><p class="inspector-intro">One idea. Connected from intent to delivery.</p><div class="spine-list">${UNIVERSAL.map((kind,i)=>{const found=d.sections.find(x=>x.kind===kind);return `<button class="spine-node ${found?.content?'filled':''} ${section?.kind===kind?'current':''}" data-action="select" data-id="${esc(found?.id??d.sections[0].id)}"><span class="node-dot">${found?.content?icon('check'):String(i+1)}</span><span>${NAMES[kind]}</span></button>`;}).join('')}</div><div class="spine-summary"><span>${filled} of 10 stages authored</span><span>Not yet audited</span></div><hr><div class="eyebrow">SELECTED SECTION</div><h3>${esc(section?.title)}</h3><p class="inspector-note">${section?.locked?'A protected decision. Unlock explicitly before changing its content.':`This section can change. The other ${d.sections.length-1} sections are read-only context.`}</p><div class="context-pair"><span>Write access</span><strong>1 section</strong></div><div class="context-pair"><span>Read context</span><strong>${d.sections.length} sections</strong></div><div class="section-actions">${btn('lock',section?.locked?'Unlock section':'Lock decision',section?.locked?'unlock':'lock','quiet',this.canWrite?'':'disabled')}${btn('undo','Restore previous','undo','quiet',this.canWrite?'':'disabled')}</div><div class="inspector-foot">${icon('info')}Every change is proposed before it is committed.</div></aside>`;}
  publish(){const s=this.s,a=s.audit,blockers=a?.findings.filter(f=>f.severity==='blocker')??[],warnings=a?.findings.filter(f=>f.severity==='warning')??[];const reviewed=a?.semantic.status==='completed'&&a?.freshReader.status==='completed';const ready=a&&!blockers.length&&reviewed&&(warnings.length===0||s.ack);return `<main class="publish-screen"><div class="publish-heading"><div class="eyebrow">${icon('file')}PUBLISH / COMPILED FROM DRAFT</div><h1>Give the idea a spine.</h1><p>A single, traceable build contract. Nothing silently rewritten. Nothing left behind.</p></div><div class="publish-grid"><div class="artifact-column"><section class="target-card" aria-label="Build target"><div><label for="target">Build with</label><select id="target">${[['codex','Codex'],['antigravity','Antigravity'],['generic','Any capable builder']].map(([value,label])=>`<option value="${value}" ${s.target===value?'selected':''}>${label}</option>`).join('')}</select></div><div><label for="format">Text format</label><select id="format"><option value="md" ${s.format==='md'?'selected':''}>BUILD.md</option><option value="txt" ${s.format==='txt'?'selected':''}>BUILD.txt</option></select></div><div><label for="context">Context allowance</label><input id="context" type="number" min="2048" max="2000000" value="${s.context}"></div><div><label for="reserve">Host + output reserve</label><input id="reserve" type="number" min="1024" value="${s.reserve}"></div><p class="target-disclaimer">User-configured capacity, not a model specification. UTF-8 byte ceiling is conservative for byte-based tokenizers; verify the actual target limit.</p></section><section class="compiled-artifact" aria-label="Compiled build contract"><div class="artifact-toolbar"><span>${icon('document')}${a?`BUILD.${s.format}`:'Build contract'}</span><span>${a?`${number(a.compiled.budget.units)} budget units`:'Run audit to compile'}</span></div>${a?`<pre class="artifact-source" tabindex="0" aria-label="Read-only compiled source">${esc(a.compiled.content)}</pre>`:`<div class="compile-empty">${icon('file')}<h2>Compile the whole idea.</h2><p>The target compiler preserves your source and checks it against the selected project spine.</p>${btn('audit','Compile & audit','check','primary',s.busy?'disabled':'')}</div>`}<div class="artifact-footer"><span>Source ${a?shortHash(a.sourceHash):'not compiled'}</span><span>${a?`Revision ${a.revision}`:'Immutable when published'}</span></div></section><div class="export-actions"><span>${s.release?'Audited release created':a?'A draft export carries its limitations with it.':'Source remains the authority.'}</span>${btn('export','Export draft','download','quiet',!a||s.busy?'disabled':'')}${btn('publish','Publish BUILD','check','primary',!ready||!this.canPublish||s.busy?'disabled':'')}</div></div>
    <aside class="audit-panel" aria-label="Audit results"><div class="audit-panel-heading"><h2>The whole-picture check</h2>${icon('link')}</div><p>Audit the connections, not just the outline.</p><div class="audit-status ${blockers.length?'blocked':ready?'passed':''}">${icon(blockers.length?'alert':ready?'check':'info')}<div><strong>${!a?'Not compiled':blockers.length?`${blockers.length} blocking ${blockers.length===1?'finding':'findings'}`:reviewed?'Review gates complete':'Structure checked'}</strong><span>${!a?'Choose a target, then run the audit.':!reviewed?'Model review has not run.':ready?'Eligible for an audited plan release.':'Review remaining findings below.'}</span></div></div>
    <div class="audit-gates">${[['Spine & source coverage',!!a],['Explicit requirement references',!!a&&!a.findings.some(f=>['UNPROVEN_REQUIREMENT','TRACEABILITY'].includes(f.code))],['Context allowance',!!a&&a.compiled.budget.fits],['Semantic alignment',a?.semantic.status==='completed'],['Fresh-reader review',a?.freshReader.status==='completed']].map(([name,pass])=>`<div><span class="gate-icon ${pass?'pass':''}">${icon(pass?'check':'clock')}</span><span>${name}</span><small>${pass?'Checked':'Not run'}</small></div>`).join('')}</div>
    ${a?.findings.length?`<div class="findings"><div class="eyebrow">FINDINGS · ${a.findings.length}</div>${a.findings.map(f=>`<button class="finding ${f.severity}" data-action="${f.sectionIds.length?'select':'add-section'}" data-id="${esc(f.sectionIds[0]??'')}"><span class="finding-label">${icon(f.severity==='blocker'?'alert':'info')}${esc(f.severity)} <span>${esc(f.origin)}</span></span><strong>${esc(f.message)}</strong><span class="finding-action">${f.sectionIds.length?'Resolve in Draft':'Add missing source'} ${icon('chevron')}</span></button>`).join('')}</div>`:''}
    <label class="review-option"><input id="semantic" type="checkbox" ${s.semantic?'checked':''} ${s.session.provider==='rehearsal'||!this.canWrite?'disabled':''}><span>Include model + fresh-reader review<small>${s.session.provider==='rehearsal'?'Connect a live provider to enable. No simulated passes.':'Two metered API requests. Reviews can still miss errors.'}</small></span></label>
    ${warnings.length?`<label class="review-option"><input id="ack" type="checkbox" ${s.ack?'checked':''}><span>I have reviewed the ${warnings.length} remaining warning${warnings.length===1?'':'s'}.</span></label>`:''}
    ${btn('audit',s.busy?'Checking…':'Run audit','check','audit-button',s.busy?'disabled':'')}<p class="audit-limit">An audited plan is not a verified product. Execution, legal, scientific, physical and participant claims need their own evidence.</p></aside></div></main>`;}
  dialog(){const s=this.s;let title='',content='';
    if(s.dialog==='create'){title='What are we making?';content=`<p>Start with an idea. Document gives it a structure you can shape in language.</p><label for="new-title">Document name</label><input id="new-title" maxlength="120" placeholder="A name for the project" autofocus><label for="new-profile">Project spine</label><select id="new-profile">${Object.entries(s.session.profiles).map(([id,p])=>`<option value="${id}">${esc(p.label)}</option>`).join('')}</select><label for="new-goal">The starting idea</label><textarea id="new-goal" rows="4" maxlength="10000" placeholder="Describe what should exist, who it is for, and what must stay true."></textarea><p class="fine-print">${s.session.provider==='rehearsal'?'Rehearsal creates an honest starting structure. It does not pretend to generate a finished plan.':'A live model will draft the selected spine. This can incur API charges.'}</p><p class="form-error" id="create-error" role="alert"></p><div class="dialog-actions">${btn('example','Explore an example','','quiet')}${btn('create-submit','Create Document','plus','primary')}</div>`;}
    if(s.dialog==='about'){title='Document, by Language Canvas';content=`<img src="${LOGO}" width="56" height="56" alt="Original Document glyph"><h3>Click defines scope.<br>Language defines change.</h3><p>An independent, working proposal for an instruction-native Document type in OpenAI’s Spaces interface. This reference shell is not the actual OpenAI product and does not install a native sidebar item.</p><p>First-party source is reserved for an OpenAI-exclusive license. No OpenAI endorsement, partnership or trademark ownership is implied.</p><p class="fine-print">Version 1.0.0 · original iconography · system typography<br>Source: bohselecta/OAI-text-doc</p>`;}
    if(s.dialog==='connection'){title='Workspace connection';content=`<div class="connection-state">${icon('info')}<strong>${s.session?.provider==='rehearsal'?'Rehearsal, not a live model':'Live model connection'}</strong></div><p>${s.session?.provider==='rehearsal'?'No text leaves this server for inference. Supported rehearsal instructions: “Make this more concise”, “Append: …”, “Replace with: …”, and “Define recovery behavior” on a recovery section.':'Instructions and selected document context are sent to the configured model service. Runtime usage may incur API charges.'}</p><h3>Connect through the host</h3><p>Set DOCUMENT_PROVIDER=openai, OPENAI_API_KEY and OPENAI_MODEL on the server, then restart. Never paste a provider key into a document or browser. A ChatGPT subscription is not assumed to pay runtime API charges.</p><p>For production, the host supplies short-lived signed identity and workspace claims. Local identity is restricted to loopback development.</p><p class="fine-print">Model: ${esc(s.session?.model??'not connected')}<br>Role: ${esc(s.session?.actor.role??'not signed in')}</p>`;}
    if(s.dialog==='profiles'){title='Give this project the right spine';content=`<p>Combine the disciplines your project actually needs. New profiles add missing stages; changing a profile never deletes existing source.</p><div class="profile-choices">${Object.entries(s.session.profiles).map(([id,p])=>`<label><input type="checkbox" name="profile" value="${id}" ${s.doc.profiles.includes(id)?'checked':''}><span><strong>${esc(p.label)}</strong><small>${esc(p.check)}</small></span></label>`).join('')}</div><p id="profile-error" class="form-error" role="alert"></p><div class="dialog-actions">${btn('close-dialog','Cancel')}${btn('profiles-save','Update spine','check','primary',!this.canWrite?'disabled':'')}</div>`;}
    if(s.dialog==='section'){title='Add a semantic section';content=`<p>Create an addressable part of the idea. Its content is authored with instructions, not typed directly into the document.</p><label for="section-title">Section name</label><input id="section-title" maxlength="100" placeholder="For example, Offline recovery" autofocus><label for="section-kind">Role in the project</label><select id="section-kind">${KINDS.map(k=>`<option value="${k}">${NAMES[k]}</option>`).join('')}</select><p id="section-error" class="form-error" role="alert"></p><div class="dialog-actions">${btn('close-dialog','Cancel')}${btn('section-save','Add section','plus','primary')}</div>`;}
    if(s.dialog==='history'){title='A history with intent';content=`<p>${s.history?.valid?'Hash chain verified for the stored events.':'Hash chain verification failed.'} Restoring a section creates a new revision; it never erases history.</p><div class="history-list">${[...(s.history?.entries??[])].reverse().map(h=>`<div class="history-event"><span class="history-dot">${icon(h.type==='section.changed'?'document':'clock')}</span><div><strong>${esc(h.type.replaceAll('.',' '))}</strong><p>${esc(h.detail.instruction??h.detail.sectionId??`Document revision ${h.revision}`)}</p><small>r${h.revision} · ${esc(h.actor)} · ${date(h.at)}</small><code>${shortHash(h.hash)}</code></div></div>`).join('')}</div><p class="fine-print">A database hash chain is not a signed, externally anchored audit ledger. The host supplies retention and external integrity anchoring.</p>`;}
    return `<dialog aria-labelledby="dialog-title"><header><h2 id="dialog-title">${title}</h2>${btn('close-dialog','','close','icon-button','aria-label="Close dialog"')}</header>${content}</dialog>`;
  }
  render(){
    const s=this.s,scroll=this.root.querySelector('.document-scroll')?.scrollTop??0,publishScroll=this.root.querySelector('.publish-screen')?.scrollTop??0;
    const active=this.root.activeElement,activeId=active?.id,selection=active?.selectionStart;
    const embedded=this.hasAttribute('embedded');
    this.root.innerHTML=`<link rel="stylesheet" href="${STYLE}"><div class="app ${s.theme} ${!s.sidebar?'sidebar-closed':''} ${embedded?'embedded':''}" ${s.busy?'aria-busy="true"':''}><a class="skip-link" href="#workspace">Skip to document</a>${!embedded?this.rail()+this.sidebar():''}<div class="workspace" id="workspace" tabindex="-1">${s.doc?this.toolbar():''}${s.error?`<div class="error-banner" role="alert">${icon('alert')}<span>${esc(s.error.message)}</span>${btn('refresh','Refresh')}${btn('close-notice','','close','icon-button','aria-label="Dismiss error"')}</div>`:''}${s.doc?(s.mode==='draft'?this.draft():this.publish()):`<main class="welcome"><img src="${LOGO}" width="64" height="64" alt="Document"><div class="eyebrow">LANGUAGE CANVAS</div><h1>The document is<br>what you make things with.</h1><p>Turn an idea into a buildable contract. One section at a time.</p>${s.session?btn('new','Create a Document','plus','primary',!this.canWrite?'disabled':''):'<p>Connecting to the document service…</p>'}</main>`}<footer class="module-footer"><span>Document <span class="footer-dot">·</span> Independent proposal for OpenAI</span>${btn('connection',s.session?.provider==='rehearsal'?'Rehearsal mode':'Provider connected','','status-button')}</footer></div>${s.notice?`<div class="toast" role="status">${icon('check')}<span>${esc(s.notice)}</span>${btn('close-notice','','close','icon-button','aria-label="Dismiss notification"')}</div>`:''}<input type="file" id="import-file" accept=".md,.txt,.json" hidden>${s.dialog?this.dialog():''}<span class="sr-only" role="status" aria-live="polite">${s.busy?'Working':s.selected?`Selected ${esc(this.section?.title)}`:'Ready'}</span></div>`;
    const scroller=this.root.querySelector('.document-scroll');if(scroller)scroller.scrollTop=scroll;
    const publisher=this.root.querySelector('.publish-screen');if(publisher)publisher.scrollTop=publishScroll;
    if(activeId&&!s.dialog){const el=this.root.getElementById(activeId);if(el&&!el.disabled){el.focus({preventScroll:true});if(typeof selection==='number'&&el.setSelectionRange&&el.tagName==='TEXTAREA')el.setSelectionRange(selection,selection);}}
    if(s.dialog){const dialog=this.root.querySelector('dialog');dialog.addEventListener('cancel',e=>{e.preventDefault();this.closeDialog();},{once:true});dialog.showModal();}
  }
}
customElements.define('language-document',DocumentModule);
